version: '3.0'
services:
    ebook-mysql:
        image: mysql:latest
        command: --max_allowed_packet=52505856 --bulk_insert_buffer_size=52505856
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=ebook
            - MYSQL_USER=demo
            - MYSQL_PASSWORD=demo
        ports:
            - 3306:3306
        container_name: mysql   
    discovery-service:
        build: ./discovery-server
        entrypoint: /wait-for-it.sh -t 5000 mysql:3306 -- java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        ports: 
            - 8761:8761
        links: 
            - ebook-mysql:mysql
        container_name: discovery_service
    user-service:
        build: ./user-service
        entrypoint: /wait-for-it.sh discovery-service:8761 -- java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        links:
            - ebook-mysql:mysql
        depends_on: 
            - discovery-service
        ports:
            - 8000:8000
        container_name: user_service    
    blog-service:
        build: ./blog-service
        entrypoint: /wait-for-it.sh user-service:8000 -- java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar        
        depends_on:
            - discovery-service
            - user-service
            - ebook-mysql            
        links: 
            - ebook-mysql:mysql
        ports:
            - 8001:8001
        container_name: blog_service
    gateway-service:
        build: ./zuul-gateway
        entrypoint: /wait-for-it.sh blog-service:8001 -- java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar app.jar
        depends_on:
            - discovery-service
            - user-service
            - blog-service            
        ports: 
            - 8765:8765
        container_name: gateway_service
    client-service:
        build: ./ebook-client
        ports: 
            - 4200:80
        container_name: client_service

networks:
  default:
    driver: bridge