spring:
  profiles: container
  datasource:
    url: jdbc:mysql://mysql:3306/epharma?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: demo
    password: demo
    initialize: true