apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    app: blog-service
spec:
  type: NodePort
  ports:
    - port: 9009
  selector:
    app: blog-service
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
      - name: blog-service
        image: bapinaidu/blog-service
        ports:
        - containerPort: 9009