apiVersion: v1
kind: Service
metadata:
  name: ebook-client
  labels:
    app: ebook-client
spec:
  type: NodePort
  ports:
    - port: 9090
  selector:
    app: ebook-client
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ebook-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebook-client
  template:
    metadata:
      labels:
        app: ebook-client
    spec:
      containers:
      - name: ebook-client
        image: bapinaidu/ebook-client
        ports:
        - containerPort: 9090