apiVersion: v1
kind: Service
metadata:
  name: log-service
  labels:
    app: log-service
spec:
  type: NodePort
  ports:
    - port: 9008
  selector:
    app: log-service
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
      - name: log-service
        image: bapinaidu/log-service
        ports:
        - containerPort: 9008